### ISSUE TITLE
jointのコード一部修正

### ISSUE THREAD

**Issue by ikeay** [vuildjp/design_tool#17]
# Description / 説明
- 少し不完全な部分があるので改善する

# Solution / 解決策
- `return`したあとは処理が実行されないので、そのあとに書かれている処理を修正する
- `return`２回されているところも、一番上のreturnまでしか実行されないので修正する
- `init`内部でやられていることが多すぎるので、機能ごとに切り出して書く
- このクラスを実行するときに必要な情報が分かると、コードの可読性があがるので、外部入力箇所はinitに引数として持たせる
- 可能であれば、最終的にrunなどのメソッドに処理をまとめて、そこでレンダリングのFalse, Trueを行う。
- 内部でしか使わない（外部から呼び出さない）メソッドに関しては、メソッド名の頭に`_`をつける

**Comment by ikeay** [comment]
あと、以下のバグがあるようです。

- Rhinoコマンド入力で実行すると最初の1回だけコマンド3回分実行される（2回目からは1回ずつじ実行される）。
- コマンドの途中でesc押してキャンセルすると、エラーがでてコマンドが実行されなくなる

２つ目に関してですが、これは用意した`run`メソッドのなかで、エラー処理を行うのが良いような気がします。
```
def run():
    try:
    # コマンドの実行処理
    except KeyboardInterrupt(e):
        print '処理が中断されました: ' + e
    except Exception(e):
        print '不明なエラーが発生しました: ' + e
```

**Comment by kbysknhr** [comment]
確認ありがとうございます。
修正します。
バグについては、僕のほうでもプラグイン化しないと検証できないと思うので、次回MTGでその辺を共有してからでしょうか。

**Comment by kbysknhr** [comment]
Solution / 解決策に書かれていることと、runメソッドの導入をやりました。
runは、クラスの中に入れるので正しいでしょうか？

**Comment by ikeay** [comment]
先日指摘した、hozo.pyのif 以下に書かれたコードと、cmd.pyのrun command以下のコードに相違があるなどではないですか？

**Comment by takano-vuild** [comment]
そうそう、下記のような書き方であってますか？

hozo.py
```
if __name__== "__main__":
    result = Hozo()
    result.run()
```

hozo_cmd.py
```
def RunCommand( is_interactive ):
  result = hozo.Hozo()
  result.run()
```

今起きているバグは
・起動後1回目のコマンド実行時、コマンドのサイクルが2回繰り返される。
・コマンド実行→引数入力後、オブジェクトが反映されず。と思いきやescキーを押すと反映される。

**Comment by maxorange** [comment]
hozo_cmd.py の一番下の行にある ```RunCommand(True)``` が2回繰り返される原因だと思います。これは Rhino Python Editor でデバッグするとき用で配布時にはコメントアウトするか削除する必要があるみたいです。
