### ISSUE TITLE
[align] オフセットする

### ISSUE THREAD

**Issue by ikeay** [vuildjp/design_tool#24]
# Description / 説明

- オフセットする

# Solution / 解決策

- オフセット込みでオブジェクトをバウンディングボックスしてから処理する

**Comment by yuri4817** [comment]
![img_0623](https://user-images.githubusercontent.com/26829709/40531445-6d09981a-6037-11e8-9d64-b9af5492edf2.JPG)
オフセット値の設定ですが、秋吉さんと話したところ*ミル幅×10㎜(default) = オフセット値*で書いていきます。
また、値をGUI上でパラメーター化できるようにしたいのですがモッピーさんの方でミル幅の変数名はなんて定義されてましたか？



>

**Comment by maxorange** [comment]
ミル幅の変数名は `mill_diameter` としています。

https://github.com/vuildjp/design_tool/blob/aec80328995a38a717f267a80faf0b3394afb3c8/dev/cam/generate_path.py#L23

**Comment by kbysknhr** [comment]
@ikeay  守矢くんがやってくれたので、よろしければCloseしちゃってください

**Comment by ikeay** [comment]
@kbysknhr プルリクがマージされれば自動で閉まります

**Comment by kbysknhr** [comment]
なるほど！
