### ISSUE TITLE
処理が重くなる問題

### ISSUE THREAD

**Issue by ikeay** [vuildjp/design_tool#7]
# Description / 説明
- プログラムを実行すると処理が重くなる

# Solution / 解決法
- 早くするコマンドがあったかも？

**Comment by ikeay** [comment]
ドキュメント読んでてこれかなと思ったんですが、違うかな
rs.EnableRedraw(False)

**Comment by kbysknhr** [comment]
正にそのコマンドです！
オフィシャルのサンプルコードにも使われてました。
https://wiki.mcneel.com/developer/scriptsamples/addcurveendpoints
