### ISSUE TITLE
どうすればAddon化できるのか調べる

### ISSUE THREAD

**Issue by ikeay** [vuildjp/design_tool#8]
# Description / 説明
- どうすればAddon化できるのか調べる

# Procedure / 手順
- [x] どうすればAddon化できるのか調べる
- [x] ライブラリはどうパッキングするのか調べる
- [x] それにあわせてデータ構造を変更する

**Comment by ikeay** [comment]
ぽいのでてきたこれかな
http://developer.rhino3d.com/guides/rhinopython/creating-rhino-commands-using-python/#creating-an-rhi-installer

**Comment by ikeay** [comment]
↑のドキュメント読むと、Pythonでプラグインを作る際は、以下のファイル構成が基本のようです。

MyPlugin
└ dev/
     ├__plugin__.py
     ├ ***_cmd.py
     ├ ***_cmd.py
     ├ ***_cmd.py
     ├ ***_cmd.py
    └ ***_cmd.py

Rhino Python Editorの新規ファイルからCommandをつくると、自動でプラグインフォルダ（プラグイン名（上の例ではMyPlugin）+GUID）も生成されるようです。
（Empty Scriptからは未検証ですが、多分こちらも同じように生成されるのだと思います）

プラグイン自体はこれをベースに作っていくことができ、配布もこのプラグインをZIPファイルにして、使う人は同じ場所で解凍すれば使えるようになるみたいです。

また、パッケージ化して配布することもでき、今回のプロジェクトの場合はそうした方が良いかなとも思っています。
その場合は、プラグインファイル配下のdevフォルダの中に`__plugin__.py` というファイルを用意します。
このファイルにはさきほどのGUIDを含んだ情報などを明記します。

```
id="{146e099d-760d-4a6c-8662-96119f3fd62f}"
version="1.0.0.1"
title="MyNewCommand"
```

この`dev`フォルダをzipにして、拡張子を`.zip`から`.rhi`に変更する。

以下は疑問点なので、実際の環境で試して欲しいです。
- 上記構造であってるのか？
- ***_cmd.pyは外のファイルや他のディレクトリのファイルをimportできるのか

**Comment by ikeay** [comment]
完成形のイメージとしては、あるコマンドを打つとプラグイン内のコマンドがすべて呼べるGUIが起動する。ただし、呼ぼうと思えば他のコマンドもコマンド単体でも呼べる。みたいな感じかな。

**Comment by takano-vuild** [comment]
昨日の一連の作業をとりあえずアップしておきます。

RhinoPythonからNew→Commandで作成すると、
<C:\Users\AppData\Roaming\McNeel\Rhinoceros\6.0\Plug-ins\PythonPlugins>
フォルダ内にパッケージが作成されます。
![RhinoPythonからCommandで作成するとパッケージができます。](https://github.com/takano-vuild/image/blob/master/design_tool/2018-05-07_18h02_07.png)

作成された.pyファイルの末尾に<RunCommand(True)>を挿入すると、ライノのコマンドとして認識される。
![コマンドになる。](https://github.com/takano-vuild/image/blob/master/design_tool/2018-05-07_18h09_23.png)

作成されたフォルダ内のdev内に"__plugin__.py"を作成。以下の内容を記述。
![__plugin__.py](https://github.com/takano-vuild/image/blob/master/design_tool/2018-05-07_18h36_55.png)

devフォルダを圧縮し、.rhiファイルを作成し解答すると以下のエラーがでる。
![ERROR](https://github.com/takano-vuild/image/blob/master/design_tool/2018-05-07_18h14_48.png)

**Comment by ikeay** [comment]
予期せぬエラーw 
気になるのが、

- これ、いますでにインストール済みだから入らないとかあります？新しい環境だと入るとかないですか？
- devに ***_cmd.py をふくめたらどうですか？

**Comment by ikeay** [comment]
ご確認ありがとうございます！

それは謎ですね…
お手数ですが、フォーラムで確認頂くことは可能ですか？

**Comment by maxorange** [comment]
よこからすみません。ちょっと気になって僕の環境でも試してみたのですが、```dev``` フォルダを圧縮するのではなく、```dev``` フォルダの中のファイルを全選択して圧縮したらインストールできました。

**Comment by ikeay** [comment]
なるほどｗ
超絶！！ありがとうございます！！！！！！！！

あとは、***_cmd.pyは外のファイルや他のディレクトリのファイルをimportできるのかっていうことがきになっているのですが、こちらはどうだかわかりますか？

**Comment by takano-vuild** [comment]
うおお、そういうことか...w
ありがとうー！！

> あとは、***_cmd.pyは外のファイルや他のディレクトリのファイルをimportできるのかっていうことがきになっているのですが、こちらはどうだかわかりますか？
すいません、これまだ試せてませんー

**Comment by ikeay** [comment]
お手すきの際で構わないのでご確認いただけると！

**Comment by takano-vuild** [comment]
なかなかやる時間がとれずにいましたが、下記構成で試してみてます。
![テスト構成](https://github.com/takano-vuild/image/blob/master/design_tool/2018-05-11_10h00_03.png)

**Comment by takano-vuild** [comment]
ところで、hozo_cmd.pyからhozo.pyを実行してみてるのですけど、うまく動かず。
クラスの呼び込み方が悪いのだと思うのですけど、どう書くといいのでしょうか。

これを...
https://github.com/vuildjp/design_tool/blob/master/joint/hozo.py

こんな感じか
`import rhinoscriptsyntax as rs
import Rhino
from src import hozo

__commandname__ = "hozo"

# RunCommand is the called when the user enters the command name in Rhino.
# The command name is defined by the filname minus "_cmd.py"
def RunCommand( is_interactive ):
  hozo.Makehozo()

  
  # you can optionally return a value from this function
  # to signify command result. Return values that make
  # sense are
  #   0 == success
  #   1 == cancel
  # If this function does not return a value, success is assumed
  return 0
RunCommand(True)`

こんな感じでサクッと実行されるかと思った
`import rhinoscriptsyntax as rs
import Rhino
from src import hozo

__commandname__ = "hozo"

# RunCommand is the called when the user enters the command name in Rhino.
# The command name is defined by the filname minus "_cmd.py"
def RunCommand( is_interactive ):
  hozo_ins = hozo.Makehozo()
  hozo_ins.makehozo()
  hozo_ins.makehole()
  hozo_ins.makehozosholes()
  
  # you can optionally return a value from this function
  # to signify command result. Return values that make
  # sense are
  #   0 == success
  #   1 == cancel
  # If this function does not return a value, success is assumed
  return 0
RunCommand(True)`

**Comment by takano-vuild** [comment]
```
# -*- coding: utf-8 -*-
import rhinoscriptsyntax as rs
import Rhino
from src.hozo import Makehozo

__commandname__ = "hozo"

# RunCommand is the called when the user enters the command name in Rhino.
# The command name is defined by the filname minus "_cmd.py"
def RunCommand( is_interactive ):
  Makehozo()
  
  # you can optionally return a value from this function
  # to signify command result. Return values that make
  # sense are
  #   0 == success
  #   1 == cancelO
  # If this function does not return a value, success is assumed
  return 0
RunCommand(True)
```

こういうことですよね。結果は同じですー。
どちらの方法でもosu、mesuの選択、offset、mil幅の入力は出るので、実行はされているようですが...

**Comment by ikeay** [comment]
なるほど、hozo.py 単体だと動きますか？ちなみに、makehosoとmakeholeはreturn後にレンダリングをtrueしてるので、ちゃんとこの処理が描かれてるmakehozoholesを実行しないといけないです

**Comment by maxorange** [comment]
hozo.py 単体は動きます。高野さんの環境でも単体で動くかどうか気になります。

**Comment by takano-vuild** [comment]
```
if __name__ == "__main__":
    result = Makehozo()
    result.makehozosholes()
```
この下2行は`if __name__ == "__main__`に含めなくてよい気がしてやってみましたが動作せずです。

**Comment by ikeay** [comment]
ごかくにんありがとうございます。
ちなみに、`if __name__=="__main__":`以下はhozo.pyやarare.py単体で実行したときのみ実行される記述です。

では、
```
MyPlugin
└ dev/
     ├__plugin__.py
     ├ hozo_cmd.py#
     ├ arare_cmd.py
     ├ …
     ├ hozo - hozo.py
     ├ arare - arare.py
    └ …
```
みたいな構造で良さそうですね！

**Comment by ikeay** [comment]
上でご指摘頂いたものはjointコード修正用Issueに反映させておきました。
https://github.com/vuildjp/design_tool/issues/17

**Comment by ikeay** [comment]
直下だとgithub用の無駄なコードが入るので、必要なものだけdevディレクトリにわけて開発を進めていきましょうか！
今、階層分けしますね。__plugin__.pyの必要な情報は後から足していきましょう！！

**Comment by ikeay** [comment]
ライブラリに関してですが、libフォルダを作るので、そこに追加していきましょう。
