### ISSUE TITLE
Rectpackを導入してみる

### ISSUE THREAD

**Issue by ikeay** [vuildjp/design_tool#9]
# Description / 説明
Rectpackを導入してみる

**Comment by yuri4817** [comment]
rect_Packを実装しました！確認お願いします。
次は多種類のobjectで試してみます。例えば、円や三角で試してみます。

**Comment by ikeay** [comment]
確認します！

**Comment by yuri4817** [comment]
`## Windows
Desktop.ini
Thumbs.db

## Mac
.DS_Store

## python
__pycache__
*.pyc

# PyCharm
.idea`
このコードを入れると日本語がエラーおきます。
これってどういう意味なんですか？

**Comment by yuri4817** [comment]
## Windows
Desktop.ini
Thumbs.db

## Mac
.DS_Store

## python
__pycache__
*.pyc

# PyCharm
.idea

このコードをいれると日本語がエラーおきます。
これはどんな意味のコードなんですか？

**Comment by yuri4817** [comment]
文字がなぜか大きくなりましたが笑
それと上記のコードを抜いて実行しても「インデックスが配列の境界外です。」と表示されるので調整します。

**Comment by ikeay** [comment]
これは .gitignoreというファイルに記載するものです。無駄なファイルをgitにaddしないために使います！

**Comment by ikeay** [comment]
https://github.com/vuildjp/design_tool/blob/81e6c7cc10a13e6b1989d1552ad80ec2b311e7e5/alignment/alignment_rectpack.py

**Comment by ikeay** [comment]
これ実行したら何行目でエラー出ますか？

**Comment by yuri4817** [comment]
![image](https://user-images.githubusercontent.com/26829709/39682899-6236d018-51ed-11e8-9be5-3e492340b270.png)

line53
line72
line81
line87
になります。

**Comment by ikeay** [comment]
53行目の前で、`print self.bunding_boxes` と`print bounding_box`してもらえますか？

**Comment by yuri4817** [comment]
![image](https://user-images.githubusercontent.com/26829709/39685468-bcaa5cc6-51fd-11e8-99f4-2e306e7b5843.png)

Rhinoのコマンド書くところにprintされてますね

**Comment by ikeay** [comment]
何がプリントされてるか見たいので、コピペしてもらえますか？

**Comment by yuri4817** [comment]
[<Rhino.Geometry.Point3d object at 0x0000000000000043 [306,-512,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000044 [330,-512,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000045 [330,-312,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000046 [306,-312,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000047 [306,-512,224]>, <Rhino.Geometry.Point3d object at 0x0000000000000048 [330,-512,224]>, <Rhino.Geometry.Point3d object at 0x0000000000000049 [330,-312,224]>, <Rhino.Geometry.Point3d object at 0x000000000000004A [306,-312,224]>]
306,-512,0


1つのobject倒しでこのprintでした。
Pointのベクトル座標値ですかね？

**Comment by ikeay** [comment]
fumufumu, 遠隔デバッグで申し訳ないのですが、２つ倒すとどうなりますか？

**Comment by yuri4817** [comment]
大丈夫ですよー基本Rhino開いているのでいつでもお願いします。

これ２つです。
[<Rhino.Geometry.Point3d object at 0x000000000000005B [306,-512,0]>, <Rhino.Geometry.Point3d object at 0x000000000000005C [330,-512,0]>, <Rhino.Geometry.Point3d object at 0x000000000000005D [330,-25,0]>, <Rhino.Geometry.Point3d object at 0x000000000000005E [306,-25,0]>, <Rhino.Geometry.Point3d object at 0x000000000000005F [306,-512,224]>, <Rhino.Geometry.Point3d object at 0x0000000000000060 [330,-512,224]>, <Rhino.Geometry.Point3d object at 0x0000000000000061 [330,-25,224]>, <Rhino.Geometry.Point3d object at 0x0000000000000062 [306,-25,224]>]
306,-512,0

これ３つです。
[<Rhino.Geometry.Point3d object at 0x0000000000000063 [306,-512,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000064 [330,-512,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000065 [330,433,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000066 [306,433,0]>, <Rhino.Geometry.Point3d object at 0x0000000000000067 [306,-512,224]>, <Rhino.Geometry.Point3d object at 0x0000000000000068 [330,-512,224]>, <Rhino.Geometry.Point3d object at 0x0000000000000069 [330,433,224]>, <Rhino.Geometry.Point3d object at 0x000000000000006A [306,433,224]>]
306,-512,0

これ変化ないですね笑

**Comment by ikeay** [comment]
あれ、変化ないねｗ
入力で使ってる `ids = rs.GetObjects("Pick objects to rotate", preselect=True)` のidsはちゃんと複数入ってるなら、`print self.bunding_boxes`は複数のlistが返ってくるはずなんだよね…

**Comment by maxorange** [comment]
```self.ids``` の中に入っているオブジェクト全てを囲むバウンディングボックスが一つ返ってきているのだと思います。なので
```python
self.bunding_boxes = rs.BoundingBox(self.ids, view_or_plane=None, in_world_coords=True)
```
のところは
```python
self.bounding_boxes = []
for _id in self.ids:
    bbox = rs.BoundingBox(_id, view_or_plane=None, in_world_coords=True)
    self.bunding_boxes.append(bbox)
```
としないといけないような気がします。

**Comment by ikeay** [comment]
あ、超助かります、今反映させますね

**Comment by yuri4817** [comment]
今なんでか考えててデバックしまくってたら、答えが登場しました笑

**Comment by ikeay** [comment]
https://github.com/vuildjp/design_tool/pull/13/commits/01c0b8754277c642d1584c5a24bfe8ca48c56231

**Comment by ikeay** [comment]
更新した

**Comment by ikeay** [comment]
一度実行させてみてください！
https://github.com/vuildjp/design_tool/blob/01c0b8754277c642d1584c5a24bfe8ca48c56231/alignment/alignment_rectpack.py

**Comment by yuri4817** [comment]
![image](https://user-images.githubusercontent.com/26829709/39688246-c25a3c54-520c-11e8-9b40-ccb21ca552b3.png)

エラーが！
Message: 'AlignObjects' object has no attribute 'bunding_boxes'

Traceback:
  line 86, in align_objects, "C:\Users\vuild03\Documents\vuild tool\Yuri\alignment_rectpack3.py"
  line 92, in run, "C:\Users\vuild03\Documents\vuild tool\Yuri\alignment_rectpack3.py"
  line 98, in <module>, "C:\Users\vuild03\Documents\vuild tool\Yuri\alignment_rectpack3.py"

**Comment by ikeay** [comment]
一度全部コピペしなおしてみてください（変数名をタイプミスしてたので変えました）

**Comment by yuri4817** [comment]
あれ？エラーが変わらないです
エラーの意味が分からぬです笑

**Comment by ikeay** [comment]
エラーの意味は、「'AlignObjects'の中で'bunding_boxes'なんていう変数は定義されてない」ってことで、わたしまだひとつ変えるの忘れてたようだ…（謝罪）

**Comment by ikeay** [comment]
https://github.com/vuildjp/design_tool/pull/13/commits/e64cbeac0afff2675646052a212d82f83b8c3071

**Comment by yuri4817** [comment]
![image](https://user-images.githubusercontent.com/26829709/39688768-3fca7fbc-520f-11e8-8265-f2c097d24e42.png)

やったー成功！
ん？なんかobjectが重なりに重なってます笑

**Comment by ikeay** [comment]
議論こっちに移行します！
https://github.com/vuildjp/design_tool/pull/13

**Comment by yuri4817** [comment]
![image](https://user-images.githubusercontent.com/26829709/39796413-496abb94-5391-11e8-8aa6-567f34d884e8.png)
ミル幅のオフセットをとって配置したのですが、これはNew issueですか？

**Comment by ikeay** [comment]
そうですね。別の問題なので。このissueはそろそろ閉じようかと思います。

**Comment by ikeay** [comment]
「さらに最適化出来る方法を考える」というのは別issue化して、一旦こちらは閉じようと思います。
